version: 1
send_anonymous_usage_stats: true
ui.authentication: false
ui.forwarded_allow_ips: '*'
project_id: 8d73bee1-5b29-467d-8df7-4d6c5d24b72b
plugins:
  extractors:
  - name: tap-postgres--telemetry
    inherit_from: tap-postgres
    variant: transferwise
    pip_url: git+https://github.com/transferwise/pipelinewise-tap-postgres.git@v1.7.1
    config:
      dbname: nutritionfacts
      port: 5432
      default_replication_method: FULL_TABLE
      filter_schemas: public
    select:
    - public-nutritionfacts_birthyearstats.*
    - public-nutritionfacts_channelstatistics.*
    - public-nutritionfacts_facilitystatistics.*
    - public-nutritionfacts_genderstats.*
    - public-nutritionfacts_instance.*
    - public-nutritionfacts_iplocation.*
    - public-nutritionfacts_message.*
    - public-nutritionfacts_pingback.*
    - public-nutritionfacts_statisticspingback.*
    metadata:
      public-nutritionfacts_birthyearstats:
        replication-method: FULL_TABLE
      public-nutritionfacts_channelstatistics:
        replication-method: FULL_TABLE
      public-nutritionfacts_facilitystatistics:
        replication-method: FULL_TABLE
      public-nutritionfacts_genderstats:
        replication-method: FULL_TABLE
      public-nutritionfacts_instance:
        replication-method: FULL_TABLE
      public-nutritionfacts_iplocation:
        replication-method: FULL_TABLE
      public-nutritionfacts_message:
        replication-method: FULL_TABLE
      public-nutritionfacts_pingback:
        replication-method: FULL_TABLE
      public-nutritionfacts_statisticspingback:
        replication-method: FULL_TABLE
  loaders:
  - name: pipelinewise-target-bigquery--telemetry
    inherit_from: pipelinewise-target-bigquery
    namespace: pipelinewise_target_bigquery
    pip_url: git+https://github.com/transferwise/pipelinewise-target-bigquery.git@v1.0.1
    executable: target-bigquery
    settings:
    - name: location
    - name: dataset_id
    - name: project_id
    - name: temp_schema
    - name: default_target_schema
    - name: schema_mapping
    - name: default_target_schema_select_permission
    - name: data_flattening_max_level
    - name: batch_size
    - name: add_metadata_columns
    - name: hard_delete
    config:
      location: US
      dataset_id: ledp
      batch_size: 100000
      default_target_schema: ledp
      add_metadata_columns: true
      hard_delete: false
      project_id: telemetry-187418
      temp_schema: tmp_ledp
      schema_mapping: ""

  orchestrators:
  - name: airflow
    pip_url: apache-airflow==1.10.14 --constraint https://raw.githubusercontent.com/apache/airflow/constraints-1.10.14/constraints-3.6.txt
  transformers:
  - name: dbt
    pip_url: dbt==0.16.1
  files:
  - name: dbt
    pip_url: git+https://gitlab.com/meltano/files-dbt.git
    update:
      transform/profile/profiles.yml: false
  - name: airflow
    pip_url: git+https://gitlab.com/meltano/files-airflow.git
schedules:
- name: ip-hash
  extractor: tap-postgres--telemetry
  loader: pipelinewise-target-bigquery
  transform: run
  interval: '@once'
  start_date: 2021-03-04 17:25:38.390109
  env:
    TARGET_BIGQUERY_PROJECT_ID: telemetry-187418
